version: '2.2'

services:
  mysql:
    container_name: mysql
    image: mysql/mysql-server:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: 'pets_home'
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_HOST: 'mysql'

    volumes:
      - data:/volumes/database

    expose:
      - '3306'
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT-8080}:${PORT-8080}"

    environment:


      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
      EMAILPWD: ${EMAILPWD}
    
      PORT: ${PORT-8080}
      MYSQL_HOST: 'mysql'
      MYSQL_PWD: 'password'
      Redis_Host: 'redis'

    depends_on:
      - mysql
      - redis



  redis:
    container_name: redis
    image: redis:latest

    ports:
      - 6379:6379
volumes:
  data:
    external: true