version: '2.2'

services:
  mysql:
    container_name: petshome
    image: mysql/mysql-server:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: 'pets_home'
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_HOST: 'mysql'

    volumes:
      - "./volumes/database:/var/lib/pets_home"

    expose:
      - '3306'
  app:
    container_name: petshome
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

    environment:



      EMAILPWD: ${EMAILPWD}
    
      PORT: 8080
      MYSQL_HOST: 'mysql'
      MYSQL_PWD: 'password'
      Redis_Host: 'redis'

    depends_on:
      - mysql
      - redis



  redis:
    container_name: petshome
    image: redis:latest

    ports:
      - 6379:6379