name: Deploy


# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ docker ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/bake-action@master
        with:
          push: true
          files: ["docker-compose.yml"]

  deploy:
    runs-on: ubuntu-latest
    env:
      EMAILPWD: ${EMAILPWD}
    steps:
      - name: Executing remote command
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
          script: |
            docker-compose down
            cd IT-project-backend
            docker pull "$secrets.DOCKER_HUB_USERNAME"/petshome
            docker run "$secrets.DOCKER_HUB_USERNAME"/petshome