name: Pet's home


# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ container ]



jobs:


  build:

    runs-on: ubuntu-latest
    env:
      EMAILPWD: ${EMAILPWD}
      MYSQL_HOST: 'mysql'
      MYSQL_PWD: 'password'
      Redis_Host: 'redis'
    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          load: true
          tags: petshome:latest





   
  deploy:
    runs-on: ubuntu-latest


    steps:
      - name: Executing remote command
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
          EMAILPWD: ${EMAILPWD}
          MYSQL_HOST: 'mysql'
          MYSQL_PWD: 'password'
          Redis_Host: 'redis'

          script: |
            cd IT-project-backend
            docker stop ${{secrets.DOCKER_HUB_USERNAME}}/petshome:latest
            docker rmi ${{secrets.DOCKER_HUB_USERNAME}}/petshome:latest
           
            docker pull ${{secrets.DOCKER_HUB_USERNAME}}/petshome:latest
            docker run ${{secrets.DOCKER_HUB_USERNAME}}/petshome:latest
      

