name: Deploy


# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ docker ]

jobs:
  build:

    runs-on: macos-latest
    env:
      EMAILPWD: ${EMAILPWD}
    steps:


      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: build and push
        with:
          scripts: |

              docker-compose build 
              docker tag petshome:app "$secrets.DOCKER_HUB_USERNAME"/petshome:app
              docker tag petshome:mysql "$secrets.DOCKER_HUB_USERNAME"/petshome:mysql
              docker tag petshome:redis "$secrets.DOCKER_HUB_USERNAME"/petshome:redis
              docker push "$secrets.DOCKER_HUB_USERNAME"/petshome:app
              docker push "$secrets.DOCKER_HUB_USERNAME"/petshome:mysql
              docker push "$secrets.DOCKER_HUB_USERNAME"/petshome:redis
  deploy:
    runs-on: ubuntu-latest
    env:
      EMAILPWD: ${EMAILPWD}
    steps:
      - name: Executing remote command
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
          script: |
            
            docker pull "$secrets.DOCKER_HUB_USERNAME"/petshome
            docker-compose up --build